### ISSUE TITLE
About file output size

### ISSUE THREAD

**Issue by laterdayi** [ThexXTURBOXx/catcher_2#26]
Hello, author, I like this plugin very much, but I want to try to understand the internal principle of the plugin, I tried to output FlutterError.onError stack into the log file, but why I output more than 10,000 characters, while catcher_2 is very few and accurate, How did you do that

**Comment by ThexXTURBOXx** [comment]
If you want to take a look at the internals, I would suggest starting here:
https://github.com/ThexXTURBOXx/catcher_2/blob/master/lib/core/catcher_2.dart#L478
From, there a `Report` object is being built which then represents the current error state of the application.
That's most of the magic. However, most of that stuff is not by me, but by `jhomlala`: https://github.com/jhomlala/catcher
This project is just a fork of his project (since it is kind of abandoned, with only very few updates coming out here and then)
