### ISSUE TITLE
Current state of catcher_2

### ISSUE THREAD

**Issue by stan-at-work** [ThexXTURBOXx/catcher_2#27]
Hello,

This is just a quick question about the fork from the original catcher package.

What was the motivation that you forked catcher && Are you planning to maintain this package for a extended time ?

Greeting.

**Comment by calcitem** [comment]
Thank you for raising this question. As a developer who actively uses catcher2, I'd like to share my understanding of why someone would fork the original cacher package and their plans for maintaining it.

The original catcher package had not been maintained for a long time, which presented challenges for many developers like myself, especially regarding essential updates for security and compatibility. The advent of catcher2 has addressed these issues, providing us with a more stable and secure solution.

The motivation behind forking and creating catcher2 was to ensure ongoing support and improvements for this tool, making sure it meets both current and future development needs. Judging by their active updates and engagement, I believe the maintainers are committed to the long-term upkeep of this project.

Moreover, as part of the community, it’s evident that the maintainers encourage feedback and contributions. This not only improves the quality of the package but also strengthens community bonds. I am personally very grateful for their efforts and believe that, over time, catcher2 will continue to be enhanced and refined.

I hope this answer helps you understand the motivation behind the fork and the plans for future maintenance. If you have any suggestions or thoughts about catcher2, I’m sure the maintainers would warmly welcome your participation and feedback.

**Comment by ThexXTURBOXx** [comment]
Hello,
I forked it because upstream was not updated for quite a while and there were a few obvious bugs.
Most prominently, it was incompatible with Flutter 3.13 and also still used deprecated zones instead of the new `onError` callbacks.
All these things have been fixed in my fork.

**Comment by ThexXTURBOXx** [comment]
Ah, another response in the same minute :)
Also, thank you for the kind words! Yes, as long as I am still around, I will try my best to keep updating it to ensure compatibility with the newest updates and also standards.
I welcome any feedback, suggestions, bug reports and - of course - PRs!

Also, even though I am pretty sure everything still works correctly, I don't own any Apple devices and hence cannot test new changes on them.
Feedback or even testers and additional maintainers in that regard would be greatly appreciated.
However, as you might have noticed, catcher_2 works without any native code as of now.
Because of this, I am very positive that compatibility will be ensured to a high degree. But one can never be sure... 

But as already said - thank you @calcitem for your kind words! :)

I will close this issue to keep my issue list clean. But if you have any further questions, I will be pleased to answer them to my very best of my abilities.
