### ISSUE TITLE
deps flutter_mailer didn't support flutter 3.24.0

### ISSUE THREAD

**Issue by orz12** [ThexXTURBOXx/catcher_2#34]
## Description
After flutter upgrade, building release says:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_mailer:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:XXXXXXXXX\build\flutter_mailer\intermediates\merged_res\release\values\values.xml:194: AAPT: error: resource android:attr/lStar not found.
flutter_mailer 2.1.2 update before 8 months, I think it needs update or replace?

**Comment by ThexXTURBOXx** [comment]
Not much I can do about it - you should rather open an issue (or even better: a PR) over at `flutter_mailer`

**Comment by calcitem** [comment]
Given that the third-party Flutter library `flutter_mailer` is no longer maintained by its original author, you will need to resolve the issues by forking or cloning the library into your local project environment and making necessary adjustments. Here’s a step-by-step solution to address the problems you are facing:

### Step 1: Clone the Library Locally
First, you need to clone the library into your project. You can do this by adding the library as a submodule or simply copying the library's source code into your project directory.

1. If you choose to use Git, you can add it as a submodule:
   ```bash
   git submodule add https://github.com/<repository-url> path/to/local/flutter_mailer
   ```

2. Alternatively, download the library from its repository and integrate it into your project structure manually.

### Step 2: Update the Android SDK Version
The error regarding `android:attr/lStar not found` suggests that the library might be using features available in newer Android versions which aren't supported by the `compileSdkVersion` defined in your app.

1. Open the `build.gradle` file within the cloned `flutter_mailer` library.
2. Update the `compileSdkVersion` and `targetSdkVersion` to a version that supports this attribute (typically the latest available SDK).

   ```gradle
   android {
       compileSdkVersion 31 // or higher
       defaultConfig {
           targetSdkVersion 31 // or higher
       }
   }
   ```

### Step 3: Resolve Proguard/R8 Issues
Since Proguard/R8 rules are not matching any classes, it’s likely that these classes are either not used or are being incorrectly referenced.

1. Open the `proguard-rules.pro` file in the `flutter_mailer` library.
2. Comment out or modify the rules that are causing issues. For example:

   ```proguard
   #-keepclassmembers,allowrepackaging,allowobfuscation class * extends androidx.lifecycle.ViewModel {
   #  <init>(androidx.lifecycle.SavedStateHandle);
   #}
   #...
   ```

3. Test if the app builds successfully without these Proguard rules. If specific functionality breaks, you might need to adjust or add specific rules that correctly reference existing classes.

### Step 4: Test the Library
After making these changes, integrate and test the library with your Flutter project:

1. Run `flutter clean` to clean the build cache.
2. Build your project using `flutter build apk` or `flutter run` to ensure that the changes have resolved the issues.

**Comment by ThexXTURBOXx** [comment]
@calcitem This sounds a lot like LLM, right? :)

But yes, this is a possible way to solve this issue. Over at the original `catcher` repository, you can also find instructions on how we used to solve this back then.
`dependency_overrides` is the key here.

**Comment by calcitem** [comment]
Given the information that the library `flutter_mailer` is used within another library `catcher_2` in your Flutter project, and considering the suggestion to use `dependency_overrides`, you can address the issue directly in your project's `pubspec.yaml`. This method allows you to override the dependency version used by `catcher_2` to point to your locally modified version of `flutter_mailer`.

Here's how you can resolve the issue by modifying your `pubspec.yaml`:

### Step 1: Clone and Modify the `flutter_mailer` Library
First, clone the `flutter_mailer` library into your local project directory as described previously. Make all necessary modifications, such as updating the Android SDK version and adjusting Proguard rules.

### Step 2: Override the Dependency in `pubspec.yaml`
In your Flutter project where `catcher_2` is a dependency, add a `dependency_overrides` section in the `pubspec.yaml` file to point to your locally modified version of `flutter_mailer`.

```yaml
dependencies:
  catcher_2: any  # assuming you're using any version, specify if needed

dependency_overrides:
  flutter_mailer:
    path: path/to/local/flutter_mailer
```

### Step 3: Ensure Proper Integration
- Run `flutter pub get` to fetch all the dependencies again.
- Verify that the overridden `flutter_mailer` is being used by running `flutter pub deps` and checking that the path points to your local version.

### Step 4: Test Your Application
- After overriding the dependency, run your application to ensure that everything works as expected without the errors previously encountered.
- Test on various devices and API levels to ensure compatibility, especially given the SDK version changes.

### Step 5: Maintain and Monitor
- Since you are now relying on a locally modified library, keep track of any updates or fixes in the original `flutter_mailer` repository.
- Regularly merge important updates or security fixes into your local version to keep it up-to-date.

This method leverages `dependency_overrides` to directly address the issue without waiting for updates from the third-party library maintainers, giving you more control over the dependencies and their compatibility with your project.
