### ISSUE TITLE
Sentry breadcrumb support

### ISSUE THREAD

**Issue by MadsVETiSearch** [ThexXTURBOXx/catcher_2#41]
## Is your feature request related to a problem? Please describe.
Catcher 2 lacks support for Sentry breadcrumbs, making it harder to trace events leading to errors.

## Describe the solution you'd like
Add support for logging Sentry breadcrumbs, enabling developers to track events like user actions.

## Describe alternatives you've considered
Using Sentry's SDK directly, but this bypasses Catcher 2 and increases maintenance overhead.

## Additional context
Breadcrumbs provide a trail of events leading up to errors, essential for debugging. 
Here’s Sentry’s documentation on breadcrumbs: https://docs.sentry.io/platforms/flutter/enriching-events/breadcrumbs/.

**Comment by ThexXTURBOXx** [comment]
> increases maintenance overhead

While I agree that such a function _might_ make sense, there are many people who do use `catcher_2`, but do not use Sentry.
Adding such a function directly to `catcher_2` might confuse this fraction (probably even majority) of users as it only works in Sentry.

In addition, this would still increase the maintenance overhead anyway. Any API change in Sentry will lead to a change of the function signature within `catcher_2`, which will then again affect the user transitively.

I will close this issue because I think the best way would be to just use Sentry's function(s) directly in this particular case.
